name: .NET

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Test
      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
    - name: Report Unit Tests
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: StorefrontProductWatcher Unit Tests
        path: StorefrontProductWatcher.Tests/TestResults/test-results.trx
        reporter: dotnet-trx
